version : "3.7"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TZ=Asia/Tokyo